### ISSUE TITLE
Using "a", "b", "c" as a list/grid param throws an error

### ISSUE THREAD

**Issue by PhilippDahlinger** [ALRhub/hydra_list_sweeper#1]
```
hydra:
  sweeper:
     list_params:
       seed: "a", "b, "c"

```

throws a weird hydra error. As a workaround, use

```
hydra:
  sweeper:
     list_params:
       seed: 
          - "a"
          - "b
          - "c"

```
I try to get around to fix it.
